FROM python:3.10-slim-bullseye
WORKDIR /app
RUN apt-get update && apt-get upgrade -y && apt-get clean
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
ENTRYPOINT [ "python", "."]
CMD ["serve"]
# CMD ["train"]